# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/

resources:
  - bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureclusters.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureclustertemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremachinetemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremachinepools.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepools.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremanagedclusters.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremachinepoolmachines.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremanagedclustertemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanetemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azuremanagedmachinepooltemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureasomanagedclusters.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureasomanagedclustertemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureasomanagedcontrolplanes.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureasomanagedcontrolplanetemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureasomanagedmachinepools.yaml
  - bases/infrastructure.cluster.x-k8s.io_azureasomanagedmachinepooltemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource


patchesStrategicMerge:
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
  # patches here are for enabling the conversion webhook for each CRD
  - patches/webhook_in_azuremachines.yaml
  - patches/webhook_in_azureclusters.yaml
  - patches/webhook_in_azureclustertemplates.yaml
  - patches/webhook_in_azureclusteridentities.yaml
  - patches/webhook_in_azuremachinetemplates.yaml
  - patches/webhook_in_azuremachinepools.yaml
  - patches/webhook_in_azuremachinepoolmachines.yaml
  # - patches/webhook_in_azuremanagedmachinepools.yaml
  # - patches/webhook_in_azuremanagedclusters.yaml
  # - patches/webhook_in_azuremanagedcontrolplanes.yaml
  # +kubebuilder:scaffold:crdkustomizewebhookpatch

  # [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
  # patches here are for enabling the CA injection for each CRD
  - patches/cainjection_in_azuremachines.yaml
  - patches/cainjection_in_azureclusters.yaml
  - patches/cainjection_in_azureclustertemplates.yaml
  - patches/cainjection_in_azureclusteridentities.yaml
  - patches/cainjection_in_azuremachinetemplates.yaml
  - patches/cainjection_in_azuremachinepools.yaml
  - patches/cainjection_in_azuremachinepoolmachines.yaml
  # - patches/cainjection_in_azuremanagedmachinepools.yaml
  # - patches/cainjection_in_azuremanagedclusters.yaml
  # - patches/cainjection_in_azuremanagedcontrolplanes.yaml
  # +kubebuilder:scaffold:crdkustomizecainjectionpatch

  - patches/capicontract_in_azuremachines.yaml
  - patches/capicontract_in_azureclusters.yaml
  - patches/capicontract_in_azureclustertemplates.yaml
  - patches/capicontract_in_azuremachinetemplates.yaml
  - patches/capicontract_in_azureclusteridentities.yaml
  - patches/capicontract_in_azuremachinepools.yaml
  - patches/capicontract_in_azuremanagedmachinepools.yaml
  - patches/capicontract_in_azuremanagedclusters.yaml
  - patches/capicontract_in_azuremanagedcontrolplanes.yaml
  - patches/capicontract_in_azuremachinepoolmachines.yaml
  - patches/capicontract_in_azuremanagedclustertemplates.yaml
  - patches/capicontract_in_azuremanagedcontrolplanetemplates.yaml
  - patches/capicontract_in_azuremanagedmachinepooltemplates.yaml
  - patches/capicontract_in_azureasomanagedclusters.yaml
  - patches/capicontract_in_azureasomanagedclustertemplates.yaml
  - patches/capicontract_in_azureasomanagedcontrolplanes.yaml
  - patches/capicontract_in_azureasomanagedcontrolplanetemplates.yaml
  - patches/capicontract_in_azureasomanagedmachinepools.yaml
  - patches/capicontract_in_azureasomanagedmachinepooltemplates.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
