name: Codespell
on:
  pull_request:
permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461 # master
      with:
        skip: .git,_artifacts,*.sum
        ignore_words_file: .codespellignore
        check_filenames: true
        check_hidden: true
