# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: codecov
on:
  pull_request:
  push:
    branches:
    - main
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.22'
    - run: "PATH=/usr/local/go/bin:$PATH make test-cover"
    - uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5.0.7
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.out
        fail_ci_if_error: true
