name: Dependabot code gen

on:
  pull_request:
    branches:
      - dependabot/**
  push:
    branches:
      - dependabot/**
  workflow_dispatch:

permissions:
  contents: write # Allow to update the PR.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3 # tag=v3.2.0
    - uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # tag=v3.2.4
      name: Restore go cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Update all modules
      run: make modules
    - name: Update generated code
      run: make generate
    - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9.1.1
      name: Commit changes
      with:
        author_name: dependabot[bot]
        author_email: 49699333+dependabot[bot]@users.noreply.github.com
        default_author: github_actor
        message: 'Update generated code'
